name: GolangCIlint

on: pull_request

jobs:
  golangci-lint:
    name: GolangCI-Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ ads, crypto, serializer, core, logger, app, constraints, ds, web, stringify, runtime, codegen, kvstore, ierrors, apputils, log, lo ]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: ./${{ matrix.module }}
          version: v1.54
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--timeout=10m"
          reporter: github-pr-check
          filter_mode: nofilter
          fail_on_error: true
