name: CI

on: [pull_request]

jobs:
  go-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [ ads, crypto, serializer, core, logger, app, constraints, ds, web, stringify, runtime, codegen, kvstore, ierrors, apputils, log, lo ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
          go-version: "1.21"
    - name: Run tests core
      working-directory: ./${{ matrix.module }}
      run: go test ./... -tags rocksdb,stacktrace -count=1 -timeout 10m
